DoctorChameleon/Models/Clinic/Patient.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DoctorChameleon.Models.Clinic
{
    public class Patient
    {
        public int PatientId { get; set; }
        
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        public string Name
        {
            get
            {
                return string.Format("{0} {1}", this.FirstName, this.LastName);
            }
        }


        public virtual ICollection<Visit> Visits { get; set; }
    }
}

DoctorChameleon/Controllers/PatientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DoctorChameleon.Data;
using DoctorChameleon.Models.Clinic;

namespace DoctorChameleon.Controllers
{
    public class PatientsController : Controller
    {
        private ClinicContext db = new ClinicContext();

        // GET: Patients
        public ActionResult Index()
        {
            var patients = db.Patients.ToList();
            var visits = db.Visits;

            foreach (var patient in patients)
            {
                patient.Visits = visits.Where(v => v.PatientId == patient.PatientId).OrderBy(v => v.Date).ToList();
            }
            
            return View(patients);
        }

        // GET: Patients/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Patient patient = db.Patients.Find(id);
            patient.Visits = db.Visits.Where(v => v.PatientId == patient.PatientId).OrderBy(v => v.Date).ToList();

            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);
        }

        // GET: Patients/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Patients/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PatientId,FirstName,LastName")] Patient patient)
        {
            if (ModelState.IsValid)
            {
                db.Patients.Add(patient);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(patient);
        }

        // GET: Patients/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Patient patient = db.Patients.Find(id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);
        }

        // POST: Patients/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PatientId,FirstName,LastName")] Patient patient)
        {
            if (ModelState.IsValid)
            {
                db.Entry(patient).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(patient);
        }

        // GET: Patients/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Patient patient = db.Patients.Find(id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);
        }

        // POST: Patients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Patient patient = db.Patients.Find(id);
            db.Patients.Remove(patient);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DoctorChameleon/Controllers/VisitsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DoctorChameleon.Data;
using DoctorChameleon.Models.Clinic;
using DoctorChameleon.ViewModels;
using System.Data.Entity.Infrastructure;

namespace DoctorChameleon.Controllers
{
    public class VisitsController : Controller
    {
        private ClinicContext db = new ClinicContext();

        // GET: Visits
        public ActionResult Index()
        {
            var visits = db.Visits.Include(v => v.Patient);
            return View(visits.ToList());
        }

        // GET: Visits/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Visit visit = db.Visits.Include(v => v.Patient).Where(v => v.VisitId == id).Single();
            if (visit == null)
            {
                return HttpNotFound();
            }
            PopulatePrescribedMedications(visit);
            return View(visit);
        }

        // GET: Visits/Create
        public ActionResult Create(int? patientId)
        {
            ViewBag.PatientId = new SelectList(db.Patients, "PatientId", "Name", patientId);
            var visit = new Visit();
            visit.Medications = new List<Medication>();
            PopulatePrescribedMedications(visit);

            return View();
        }

        // POST: Visits/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "VisitId,Date,Diagnosis,PatientId")] Visit visit, string[] selectedMeds)
        {
            if (selectedMeds != null)
            {
                visit.Medications = new List<Medication>();

                foreach (var med in selectedMeds)
                {
                    var medToAdd = db.Medications.Find(int.Parse(med));
                    visit.Medications.Add(medToAdd);
                }
            }

            if (ModelState.IsValid)
            {
                db.Visits.Add(visit);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PatientId = new SelectList(db.Patients, "PatientId", "Name", visit.PatientId);
            PopulatePrescribedMedications(visit);
            return View(visit);
        }

        // GET: Visits/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Visit visit = db.Visits.Find(id);
            if (visit == null)
            {
                return HttpNotFound();
            }
            ViewBag.PatientId = new SelectList(db.Patients, "PatientId", "Name", visit.PatientId);
            PopulatePrescribedMedications(visit);
            return View(visit);
        }

        // POST: Visits/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int? id, string[] selectedMeds)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Visit visit = db.Visits.Include(v => v.Patient).Where(v => v.VisitId == id).Single();

            if (TryUpdateModel(visit, "", new string[] { "VisitId", "Date", "Diagnosis", "PatientId" }))
            {
                try
                {
                    UpdateMeds(selectedMeds, visit);

                    db.Entry(visit).State = EntityState.Modified;
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
                catch (RetryLimitExceededException)
                {
                    ModelState.AddModelError("", "Unable to save changes.");
                }
            }

            PopulatePrescribedMedications(visit);

            ViewBag.PatientId = new SelectList(db.Patients, "PatientId", "Name", visit.PatientId);
            return View(visit);
        }

        private void UpdateMeds(string[] selectedMeds, Visit visit)
        {
            if (selectedMeds == null)
            {
                visit.Medications = new List<Medication>();
                return;
            }

            var selectedMedsHS = new HashSet<string>(selectedMeds);
            var visitMeds = new HashSet<int>(visit.Medications.Select(m => m.MedicationId));

            foreach (var med in db.Medications)
            {
                if (selectedMedsHS.Contains(med.MedicationId.ToString()))
                {
                    if (!visitMeds.Contains(med.MedicationId))
                    {
                        visit.Medications.Add(med);
                    }
                }
                else
                {
                    if (visitMeds.Contains(med.MedicationId))
                    {
                        visit.Medications.Remove(med);
                    }
                }
            }
        }

        // GET: Visits/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Visit visit = db.Visits.Include(v => v.Patient).Where(v => v.VisitId == id).Single();
            if (visit == null)
            {
                return HttpNotFound();
            }
            return View(visit);
        }

        // POST: Visits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Visit visit = db.Visits.Find(id);
            db.Visits.Remove(visit);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        private void PopulatePrescribedMedications(Visit visit)
        {
            var allMedications = db.Medications;
            var prescribedMedications = new HashSet<int>(visit.Medications.Select(m => m.MedicationId));
            var viewModel = new List<VisitMedicationsVM>();

            foreach (var medication in allMedications)
            {
                viewModel.Add(new VisitMedicationsVM
                {
                    MedicationId = medication.MedicationId,
                    Name = medication.Name,
                    Prescribed = prescribedMedications.Contains(medication.MedicationId)
                });
                ViewBag.Medications = viewModel;
            }

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DoctorChameleon/Views/Patients/Create.cshtml
@model DoctorChameleon.Models.Clinic.Patient

@{
    ViewBag.Title = "Register New Patient";
}

<h2>Register New Patient</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Register" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("View All Patients", "Index")
</div>

DoctorChameleon/Views/Patients/Delete.cshtml
@model DoctorChameleon.Models.Clinic.Patient

@{
    ViewBag.Title = "Delete Patient";
}

<h2>Delete Patient</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DoctorChameleon/Views/Patients/Details.cshtml
@model DoctorChameleon.Models.Clinic.Patient

@{
    ViewBag.Title = Model.Name;
}

<h2>Patient Details</h2>

<hr />

<div>
    <h3>@Html.DisplayFor(model => model.Name)</h3>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.PatientId }) |
        @Html.ActionLink("View All Patients", "Index")
    </p>

    <hr />

    <h4>@Html.DisplayNameFor(model => model.Visits)</h4>
    <ul>
        @foreach (var visit in Model.Visits)
        {
            <li>
                @Html.ActionLink(visit.Date.ToString("dd/MM/yyyy"), "Details", "Visits", new { id = visit.VisitId }, null)
            </li>
        }
    </ul>
    @Html.ActionLink("Add New Visit", "Create", "Visits", new { patientId = Model.PatientId }, null)
</div>

DoctorChameleon/Views/Patients/Edit.cshtml
@model DoctorChameleon.Models.Clinic.Patient

@{
    ViewBag.Title = "Edit Patient";
}

<h2>Edit Patient</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PatientId)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DoctorChameleon/Views/Patients/Index.cshtml
@model IEnumerable<DoctorChameleon.Models.Clinic.Patient>

@{
    ViewBag.Title = "Registered Patients";
}

<h2>Registered Patients</h2>

<p>
    @Html.ActionLink("Register New Patient", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            Last Visit
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink(item.Name, "Details", new { id = item.PatientId })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Visits.LastOrDefault().Date)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PatientId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PatientId })
        </td>
    </tr>
}

</table>