DoctorChameleon/Models/Clinic/Visit.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DoctorChameleon.Models.Clinic
{
    public class Visit
    {
        public int VisitId { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime Date { get; set; }

        public string Diagnosis { get; set; }

        public int PatientId { get; set; }
        public Patient Patient { get; set; }

        public virtual ICollection<Medication> Medications { get; set; }
    }
}

DoctorChameleon/Controllers/MedicationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DoctorChameleon.Data;
using DoctorChameleon.Models.Clinic;

namespace DoctorChameleon.Controllers
{
    public class MedicationsController : Controller
    {
        private ClinicContext db = new ClinicContext();

        // GET: Medications
        public ActionResult Index()
        {
            return View(db.Medications.ToList());
        }

        // GET: Medications/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medication medication = db.Medications.Find(id);
            if (medication == null)
            {
                return HttpNotFound();
            }
            return View(medication);
        }

        // GET: Medications/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Medications/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MedicationId,Name")] Medication medication)
        {
            if (ModelState.IsValid)
            {
                db.Medications.Add(medication);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(medication);
        }

        // GET: Medications/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medication medication = db.Medications.Find(id);
            if (medication == null)
            {
                return HttpNotFound();
            }
            return View(medication);
        }

        // POST: Medications/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MedicationId,Name")] Medication medication)
        {
            if (ModelState.IsValid)
            {
                db.Entry(medication).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(medication);
        }

        // GET: Medications/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medication medication = db.Medications.Find(id);
            if (medication == null)
            {
                return HttpNotFound();
            }
            return View(medication);
        }

        // POST: Medications/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Medication medication = db.Medications.Find(id);
            db.Medications.Remove(medication);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DoctorChameleon/Controllers/VisitsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DoctorChameleon.Data;
using DoctorChameleon.Models.Clinic;
using DoctorChameleon.ViewModels;
using System.Data.Entity.Infrastructure;

namespace DoctorChameleon.Controllers
{
    public class VisitsController : Controller
    {
        private ClinicContext db = new ClinicContext();

        // GET: Visits
        public ActionResult Index()
        {
            var visits = db.Visits.Include(v => v.Patient);
            return View(visits.ToList());
        }

        // GET: Visits/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Visit visit = db.Visits.Include(v => v.Patient).Where(v => v.VisitId == id).Single();
            if (visit == null)
            {
                return HttpNotFound();
            }
            PopulatePrescribedMedications(visit);
            return View(visit);
        }

        // GET: Visits/Create
        public ActionResult Create(int? patientId)
        {
            ViewBag.PatientId = new SelectList(db.Patients, "PatientId", "Name", patientId);
            var visit = new Visit();
            visit.Medications = new List<Medication>();
            PopulatePrescribedMedications(visit);

            return View();
        }

        // POST: Visits/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "VisitId,Date,Diagnosis,PatientId")] Visit visit, string[] selectedMeds)
        {
            if (selectedMeds != null)
            {
                visit.Medications = new List<Medication>();

                foreach (var med in selectedMeds)
                {
                    var medToAdd = db.Medications.Find(int.Parse(med));
                    visit.Medications.Add(medToAdd);
                }
            }

            if (ModelState.IsValid)
            {
                db.Visits.Add(visit);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PatientId = new SelectList(db.Patients, "PatientId", "Name", visit.PatientId);
            PopulatePrescribedMedications(visit);
            return View(visit);
        }

        // GET: Visits/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Visit visit = db.Visits.Find(id);
            if (visit == null)
            {
                return HttpNotFound();
            }
            ViewBag.PatientId = new SelectList(db.Patients, "PatientId", "Name", visit.PatientId);
            PopulatePrescribedMedications(visit);
            return View(visit);
        }

        // POST: Visits/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int? id, string[] selectedMeds)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Visit visit = db.Visits.Include(v => v.Patient).Where(v => v.VisitId == id).Single();

            if (TryUpdateModel(visit, "", new string[] { "VisitId", "Date", "Diagnosis", "PatientId" }))
            {
                try
                {
                    UpdateMeds(selectedMeds, visit);

                    db.Entry(visit).State = EntityState.Modified;
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
                catch (RetryLimitExceededException)
                {
                    ModelState.AddModelError("", "Unable to save changes.");
                }
            }

            PopulatePrescribedMedications(visit);

            ViewBag.PatientId = new SelectList(db.Patients, "PatientId", "Name", visit.PatientId);
            return View(visit);
        }

        private void UpdateMeds(string[] selectedMeds, Visit visit)
        {
            if (selectedMeds == null)
            {
                visit.Medications = new List<Medication>();
                return;
            }

            var selectedMedsHS = new HashSet<string>(selectedMeds);
            var visitMeds = new HashSet<int>(visit.Medications.Select(m => m.MedicationId));

            foreach (var med in db.Medications)
            {
                if (selectedMedsHS.Contains(med.MedicationId.ToString()))
                {
                    if (!visitMeds.Contains(med.MedicationId))
                    {
                        visit.Medications.Add(med);
                    }
                }
                else
                {
                    if (visitMeds.Contains(med.MedicationId))
                    {
                        visit.Medications.Remove(med);
                    }
                }
            }
        }

        // GET: Visits/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Visit visit = db.Visits.Include(v => v.Patient).Where(v => v.VisitId == id).Single();
            if (visit == null)
            {
                return HttpNotFound();
            }
            return View(visit);
        }

        // POST: Visits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Visit visit = db.Visits.Find(id);
            db.Visits.Remove(visit);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        private void PopulatePrescribedMedications(Visit visit)
        {
            var allMedications = db.Medications;
            var prescribedMedications = new HashSet<int>(visit.Medications.Select(m => m.MedicationId));
            var viewModel = new List<VisitMedicationsVM>();

            foreach (var medication in allMedications)
            {
                viewModel.Add(new VisitMedicationsVM
                {
                    MedicationId = medication.MedicationId,
                    Name = medication.Name,
                    Prescribed = prescribedMedications.Contains(medication.MedicationId)
                });
                ViewBag.Medications = viewModel;
            }

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DoctorChameleon/Views/Visits/Create.cshtml
@model DoctorChameleon.Models.Clinic.Visit

@{
    ViewBag.Title = "Create Visit";
}

<h2>Create Visit</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.PatientId, "Patient", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PatientId", null, " --- Select --- ", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PatientId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Diagnosis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Diagnosis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Diagnosis, "", new { @class = "text-danger" })
            </div>
        </div><hr />

        <h4>Medications</h4>

        <div class="form-group">
            <ul>
                @foreach (var med in ViewBag.Medications)
                        {
                    <li>
                        <input type="checkbox" name="selectedMeds" value="@med.MedicationId"
                               @(Html.Raw(med.Prescribed ? "checked=\"checked\"" : "")) />
                        @med.Name
                    </li>
                }
            </ul>
        </div>

        @Html.ActionLink("Create New Medication", "Create", "Medications")

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DoctorChameleon/Views/Visits/Delete.cshtml
@model DoctorChameleon.Models.Clinic.Visit

@{
    ViewBag.Title = "Delete Visit";
}

<h2>Delete Visit</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Patient)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Patient.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Model.Date.ToString("dd/MM/yyyy")
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Diagnosis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Diagnosis)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DoctorChameleon/Views/Visits/Details.cshtml
@model DoctorChameleon.Models.Clinic.Visit

@{
    ViewBag.Title = "Visit Details";
}

<h2>Visit Details</h2>

<hr />

<div>
    <h3>@Model.Patient.Name</h3>
    <h4>@Model.Date.ToString("dd/MM/yyyy")</h4>
    
    <hr />

    <h4>@Html.DisplayNameFor(model => model.Diagnosis)</h4>
    <p>@Model.Diagnosis</p>

    <hr />

    <h4>@Html.DisplayNameFor(model => model.Medications)</h4>
    <ul>
        @foreach (var med in ViewBag.Medications)
        {
            if (med.Prescribed)
            {
            <li>
                @med.Name
            </li>
            }
        }
    </ul>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.VisitId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DoctorChameleon/Views/Visits/Edit.cshtml
@model DoctorChameleon.Models.Clinic.Visit

@{
    ViewBag.Title = "Edit Visit";
}

<h2>Edit Visit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.VisitId)

        <div class="form-group">
            @Html.LabelFor(model => model.PatientId, "Patient", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PatientId", null, " --- Select --- ", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PatientId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Diagnosis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Diagnosis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Diagnosis, "", new { @class = "text-danger" })
            </div>
        </div>

        <hr />

        <h4>Medications</h4>

        <div class="form-group">
            <ul>
                @foreach (var med in ViewBag.Medications)
                {
                    <li>
                        <input type="checkbox" name="selectedMeds" value="@med.MedicationId"
                        @(Html.Raw(med.Prescribed ? "checked=\"checked\"" : ""))
                                />
                        @med.Name
                    </li>
                }
            </ul>
        </div>

        @Html.ActionLink("Create New Medication", "Create", "Medications")

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DoctorChameleon/Views/Visits/Index.cshtml
@model IEnumerable<DoctorChameleon.Models.Clinic.Visit>

@{
    ViewBag.Title = "Visits";
}

<h2>Visits</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Patient)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Diagnosis)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td style="white-space:nowrap">
            @Html.DisplayFor(modelItem => item.Patient.Name)
        </td>
        <td style="white-space:nowrap">
            @Html.ActionLink(item.Date.ToString("dd/MM/yyyy"), "Details", new { id = item.VisitId })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Diagnosis)
        </td>
        <td style="white-space:nowrap">
            @Html.ActionLink("Edit", "Edit", new { id=item.VisitId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.VisitId })
        </td>
    </tr>
}

</table>